### ISSUE TITLE
Example for wrapping one Stream+Sink with both FramedRead and FramedWrite

### ISSUE THREAD

**Issue by rorytrent** [carllerche/tokio-serde#1]
Perhaps I'm missing something obvious but I'm finding it difficult to wrap one object which implements both Stream+Sink, with both the FramedRead and FramedWrite wrappers. If there is a simple way to do this, maybe an example could be added.

Thanks

**Comment by carllerche** [comment]
I don't understand the question. You would not wrap an obj that implements `Stream + Sink`. The helpers will provide `Stream + Sink` for you.

**Comment by rorytrent** [comment]
While I may be mistaken, here are the lines which led be to believe that FramedRead wraps a Stream and FramedWrite wraps a Sink. I would like to wrap one object which implements both Stream + Sink, with both FramedRead and FramedWrite.

https://github.com/carllerche/tokio-serde/blob/fbafd2386d525d615332941d4e62c71af90dc40c/src/lib.rs#L294-L296

https://github.com/carllerche/tokio-serde/blob/fbafd2386d525d615332941d4e62c71af90dc40c/src/lib.rs#L356-L357

**Comment by bkchr** [comment]
Is this issue still relevant?

**Comment by Lindenk** [comment]
I know this is almost a decade later but it's still unclear how to both send and receive framed data on a stream. Here's a minimal example of what I would expect to work (but doesn't):

```rust
use futures::prelude::*;
use serde::{Deserialize, Serialize};
use tokio::net::TcpListener;
use tokio_serde::formats::*;
use tokio_util::codec::{FramedRead, FramedWrite, LengthDelimitedCodec};

#[derive(Serialize, Deserialize, Debug)]
struct Message {
  x: i32,
}

#[tokio::main]
pub async fn main() {
  // Bind a server socket
  let listener = TcpListener::bind("127.0.0.1:17653").await.unwrap();

  println!("listening on {:?}", listener.local_addr());

  loop {
    let (socket, _) = listener.accept().await.unwrap();

    // Delimit frames using a length header
    let length_delimited = FramedRead::new(socket, LengthDelimitedCodec::new());

    // Deserialize frames
    let mut framed_sock =
      tokio_serde::SymmetricallyFramed::new(length_delimited, SymmetricalJson::<Message>::default());

    // Spawn a task that prints all received messages to STDOUT
    tokio::spawn(async move {
      while let Some(msg) = framed_sock.try_next().await.unwrap() {
        println!("GOT: {:?}", msg);
        // Error: Response doesn't implement Sink<'_>
        framed_sock.send(Message { x: 5 });
      }
    });
  }
}
```
